[phases.setup]
nixPkgs = [
    "python3",
    "python3Packages.pip",
    "postgresql",
    "redis",
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT"